# Generated by Django 3.1 on 2020-08-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0003_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
